// src/components/App.jsx
import { connect } from "react-redux";
import FormattedOutput from "./FormattedOutput";
import InputForm from "./InputForm";
import JsonInfo from "./JsonInfo";

function App({ formatted }) {
  return (
    <div className="w-full h-full px-4">
      <div className="h-full flex flex-wrap">
        <InputForm className="w-full h-full flex flex-col py-4 md:w-1/3 md:pr-2" />
        <div className="w-full h-full py-4 md:w-2/3 md:pl-2">
          <transition mode="out-in">
            {formatted ? <FormattedOutput /> : <JsonInfo />}
          </transition>
        </div>
      </div>
    </div>
  );
}

const mapStateToProps = (state) => ({ formatted: state.formatted });

export default connect(mapStateToProps)(App);

// src/components/App.vue
<template>
  <div class="w-full h-full px-4">
    <div class="h-full flex flex-wrap">
      <InputForm class="w-full h-full flex flex-col py-4 md:w-1/3 md:pr-2" />
      <div class="w-full h-full py-4 md:w-2/3 md:pl-2">
        <transition mode="out-in">
          <FormattedOutput v-if="formatted" />
          <JsonInfo v-else />
        </transition>
      </div>
    </div>
  </div>
</template>

<script>
import { mapState } from "vuex";
import FormattedOutput from "./FormattedOutput.vue";
import InputForm from "./InputForm.vue";
import JsonInfo from "./JsonInfo.vue";

export default {
  computed: mapState(["formatted"]),
  components: {
    JsonInfo,
    FormattedOutput,
    InputForm,
  },
};
</script>
