// src/components/FormattedOutput.jsx
import hljs from "highlight.js/lib/core";
import { createRef, useState } from "react";
import { connect } from "react-redux";

function FormattedOutput({ hasError, formatted, language }) {
  const [notification, setNotification] = useState("Copy");
  const bufferRef = createRef();
  const highlighted = hasError
    ? formatted
    : { __html: hljs.highlight(language, formatted).value };

  function copy() {
    const selection = window.getSelection();
    selection.selectAllChildren(bufferRef.current);
    document.execCommand("copy");
    selection.removeAllRanges();

    setNotification("Copied");
    setTimeout(() => setNotification("Copy"), 1500);
  }

  return (
    <div className="h-full flex flex-col">
      <div className="h-full border border-gray-500 overflow-auto">
        <pre className="h-full m-0 text-sm" ref={bufferRef}>
          {hasError ? (
            <code className="h-full hljs">{highlighted}</code>
          ) : (
            <code
              className="h-full hljs"
              dangerouslySetInnerHTML={highlighted}
            ></code>
          )}
        </pre>
      </div>
      <div className="mt-2 text-center">
        <button
          className="focus:outline-none focus:ring hover:underline text-yellow-600 cursor-pointer"
          onClick={(e) => {
            e.preventDefault();
            copy();
          }}
        >
          {notification} {formatted.length} characters
        </button>
      </div>
    </div>
  );
}

const mapStateToProps = (state) => ({
  hasError: state.hasError,
  formatted: state.formatted,
  language: state.language,
});

export default connect(mapStateToProps)(FormattedOutput);

// src/components/FormattedOutput.vue
<template>
  <div class="h-full flex flex-col">
    <div class="h-full border border-gray-800 overflow-auto">
      <pre
        class="h-full m-0 text-sm"
        ref="buffer"
      ><code v-if="hasError" class="h-full hljs">{{ highlighted }}</code><code v-else class="h-full hljs" v-html="highlighted"></code></pre>
    </div>
    <div class="mt-2 text-center">
      <a
        class="focus:outline-none hover:underline obsidian-orange cursor-pointer"
        href=""
        @click.prevent="copy"
      >
        {{ notification }} {{ formatted.length }} characters
      </a>
    </div>
  </div>
</template>

<script>
import hljs from "highlight.js/lib/core";
import { mapState } from "vuex";

export default {
  data() {
    return {
      notification: "Copy",
    };
  },
  computed: {
    ...mapState(["formatted", "language", "hasError"]),
    highlighted() {
      if (this.hasError) return this.formatted;

      return hljs.highlight(this.language, this.formatted).value;
    },
  },
  methods: {
    copy() {
      const selection = window.getSelection();
      selection.selectAllChildren(this.$refs.buffer);
      document.execCommand("copy");
      selection.removeAllRanges();

      this.notification = "Copied";
      setTimeout(() => {
        this.notification = "Copy";
      }, 1500);
    },
  },
};
</script>
