// src/components/InputForm.jsx
import { connect } from "react-redux";
import { formatInput } from "../actions";

function InputForm({ input, hasError, formatInput, className }) {
  let textareaClass =
    "w-full h-full border p-2 font-mono text-xs leading-tight obsidian-gray bg-obsidian-dark-gray resize-none";
  textareaClass += hasError ? " border-red-800" : " border-gray-800";

  return (
    <div className={className}>
      <textarea
        className={textareaClass}
        placeholder="json or xml here"
        value={input}
        onInput={(e) => formatInput(e.target.value)}
        autoFocus
      ></textarea>
      <div className="mt-2 text-center">{input.length} characters</div>
    </div>
  );
}

const mapStateToProps = (state) => ({
  input: state.input,
  hasError: state.hasError,
});

export default connect(mapStateToProps, { formatInput })(InputForm);

// src/components/InputForm.vue
<template>
  <div>
    <textarea
      class="w-full h-full border border-gray-800 p-2 font-mono text-xs leading-tight obsidian-gray bg-obsidian-dark-gray resize-none"
      :class="{ 'border-red-800': hasError }"
      placeholder="json or xml here"
      @input="formatInput"
      ref="input"
    ></textarea>
    <div class="mt-2 text-center">{{ input.length }} characters</div>
  </div>
</template>

<script>
import { mapState } from "vuex";

export default {
  computed: mapState(["input", "hasError"]),
  methods: {
    formatInput(event) {
      this.$store.commit("formatInput", event.target.value);
    },
  },
  mounted() {
    this.$refs.input.focus();
  },
};
</script>
